<?php 

// Get folder Name From Currnent Url 
$folder_name        = explode("/",$_SERVER['PHP_SELF']);
$folder_name        = $folder_name[count($folder_name)-2];

// // Database Country Table Name
$table             = "block_name_creation";

// // Include DB file and Common Functions
include '../../config/dbconfig.php';

// // Variables Declaration
$action             = $_POST['action'];

$fund_name          = "";
$is_active          = "";
$unique_id          = "";
$prefix             = "";

$data               = "";
$msg                = "";
$error              = "";
$status             = "";
$test               = ""; // For Developer Testing Purpose
function validateCSRFToken($token) {
    return isset($_SESSION['csrf_token']) && hash_equals($_SESSION['csrf_token'], $token);
}

switch ($action) {
    case 'createupdate':
        $token = $_POST['csrf_token'];
    
        // Validate CSRF token (Replace with your CSRF validation logic)
        if (!validateCSRFToken($token)) {
            die('CSRF validation failed.');
        }
    
        // Retrieve POST data
        $block_name = sanitizeInput($_POST["block_name"]);
        $description = sanitizeInput($_POST["description"]);
        $is_active = $_POST["is_active"];
        $unique_id = $_POST["unique_id"];
    
        // Initialize variables
        $status = false;
        $data = [];
        $error = "";
        $msg = "";
    
        // Prepare SQL query and parameters
        $sql = "";
        $params = [];
        $types = "";
    
        if ($unique_id) {
            // Update operation
            $sql = "UPDATE $table SET block_name = ?, description = ?, is_active = ? WHERE unique_id = ?";
            $params = [$block_name, $description, $is_active, $unique_id];
            $types = "ssis"; // Assuming block_name and description are strings, is_active is integer
        } else {
            // Insert operation
            $sql = "INSERT INTO $table (block_name, description, is_active, unique_id) VALUES (?, ?, ?, ?)";
            // $unique_id = unique_id($prefix); // Assuming unique_id is generated by a function
            $params = [$block_name, $description, $is_active, unique_id($prefix)];
            $types = "ssis"; // Assuming block_name and description are strings, is_active is integer
        }
    
        // Prepare statement
        $stmt = $mysqli->prepare($sql);
        if ($stmt === false) {
            die('MySQL prepare error: ' . $mysqli->error);
        }
    
        // Bind parameters
        $stmt->bind_param($types, ...$params);
    
        // Execute query
        if ($stmt->execute()) {
            $status = true;
            if ($unique_id) {
                $msg = "update";
            } else {
                $msg = "create";
            }
        } else {
            $error = $stmt->error;
            $msg = "error";
        }
    
        $stmt->close();
    
        // Close MySQLi connection
        $mysqli->close();
    
        // Prepare JSON response
        $json_array = [
            "status" => $status,
            "data" => $data,
            "error" => $error,
            "msg" => $msg,
            // "sql" => $sql  // Optionally include SQL query for debugging
        ];
    
        echo json_encode($json_array);
        break;
    

    case 'datatable':
        // DataTable Variables
        $length     = $_POST['length'];
        $start      = $_POST['start'];
        $draw       = $_POST['draw'];
        $limit      = $length;

        $data       = [];
       
        // Query Variables
        $json_array     = "";
        $columns        = [
            "@a:=@a+1 s_no",
            "block_name",
            "description",
            "is_active",
            "unique_id"
        ];
        $table_details = "$table , (SELECT @a:= ?) AS a";
        $where = "is_delete = 0";
        $bind_params = "i"; // Types of parameters (i for integer)
        $bind_values = [$start];
    
      
        $sql_function = "SQL_CALC_FOUND_ROWS";
        $order_by = ""; // Set the order by clause if necessary
    
        // SQL query for data fetching
        $sql = "SELECT $sql_function " . implode(", ", $columns) . " FROM $table_details WHERE $where";
        if ($limit !== "") {
            $sql .= " LIMIT ?, ?";
            $bind_params .= "ii"; // Add types for limit parameters
            $bind_values[] = $start;
            $bind_values[] = $limit;
        }
    
        $stmt = $mysqli->prepare($sql);
    
        if ($stmt === false) {
            // Handle prepare error
            $json_array = [
                "draw" => intval($draw),
                "recordsTotal" => 0,
                "recordsFiltered" => 0,
                "data" => [],
                "error" => $mysqli->error
            ];
            echo json_encode($json_array);
            break;
        }
    
        // Bind parameters dynamically
        $bind_params_arr = array_merge([$bind_params], ...array_map(function ($v) {
            return [$v];
        }, $bind_values));
        call_user_func_array([$stmt, 'bind_param'], $bind_params_arr);
    
        $stmt->execute();
        $result = $stmt->get_result();
    
        // Fetch total records
        $total_records_result = $mysqli->query("SELECT FOUND_ROWS() as total");
        $total_records = $total_records_result->fetch_assoc()['total'];
    

        if ($result) {

            $res_array = $result->fetch_all(MYSQLI_ASSOC);

            foreach ($res_array as $key => $value) {
                $value['fund_name'] = disname($value['fund_name']);
                $value['is_active'] = is_active_show($value['is_active']);
                

                $btn_update         = btn_update($folder_name,$value['unique_id']);
                $btn_delete         = btn_delete($folder_name,$value['unique_id']);

                if ( $value['unique_id'] == "5f97fc3257f2525529") {
                    $btn_update         = "";
                    $btn_delete         = "";
                } 

                $value['unique_id'] = $btn_update.$btn_delete;
                $data[]             = array_values($value);
            }
            
            $json_array = [
                "draw"              => intval($draw),
                "recordsTotal"      => intval($total_records),
                "recordsFiltered"   => intval($total_records),
                "data"              => $data,
                // "testing"           => $result->sql
            ];
        } else {
            // print_r($result);
        }
        
        echo json_encode($json_array);
        break;
    
    
        case 'delete':
            $token = $_POST['csrf_token'];
        if (!validateCSRFToken($token)) {
            die('CSRF validation failed.');
        }
            $unique_id = $_POST['unique_id'];
        
            $status = false;
            $data = [];
            $error = "";
            $msg = "";

            $is_delete = 1;
        
            // Prepare update query
            $sql = "UPDATE $table SET is_delete = ? WHERE unique_id = ?";
            $stmt = $mysqli->prepare($sql);
        
            // Bind parameters
            $stmt->bind_param("is", $is_delete,$unique_id);
        
            // Execute query
            if ($stmt->execute()) {
                $status = true;
                $msg = "success_delete";
            } else {
                $error = $mysqli->error;
                $msg = "error";
            }
        
            $stmt->close();
        
           
        
            // Prepare JSON response
            $json_array = [
                "status" => $status,
                "data" => $data,
                "error" => $error,
                "msg" => $msg,
                // "sql" => $sql
            ];
        
            echo json_encode($json_array);
            break;

    default:
        
        break;
}
    
       
?>
